import { axiforma } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "Web3 Checkout",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${axiforma.variable} antialiased`}>{children}</body>
    </html>
  );
}
