import { axiforma } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "Web3 Checkout",
  description: "Generated by create next app",
  verification: {
    google: "X2AtOOBTzlw2FDxNQCQE9wnSVuIO1LHJk15vEp8zuDM"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${axiforma.variable} antialiased`}>{children}</body>
    </html>
  );
}
